spring.application.name: sample

app.package: com.company.app

app.pubsub.clients.default:
  addresses: ${PUBSUB_ADDRESSES:simple}
  subjects: sample,foundation-service*

spring.config.import:
  - classpath:application-foundation.yml
