spring.application.name: sample

app.package: dev.soffa.foundation

app.openapi:
  info:
    title: Foundation API
    version: 0.1.0
    description: |
      ## Introduction
      Foundation Demo App. This content support markdown
      ### Level 3
      Here we come
    contact:
      name: SOFFA
      url: http://nopp
      email: noreply@soffa.io
  security:
    token-bearer: true
    oauth2:
      url: http://localhost:9000
      scopes: openid
      authorizationCode: true
  parameters:
    - name: X-TenantId
      description: Active tenant
      values: [ T1, T2 ]
      in: header

spring.config.import:
  - classpath:application-foundation.yml
