app.amqp:
  enabled: true
  clients.default:
    exchange: app
    routing: services
    vhost: ${AMQP_VHOST:/}
    addresses: ${AMQP_ADDRESSES:"localhost:5672"}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}


spring.rabbitmq:
  listener.simple.retry:
    enabled: true
    initial-interval: 2s
    max-attempts: 30
    max-interval: 300s
    multiplier: 2
  addresses: ${app.amqp.clients.default.addresses}
  username: ${app.amqp.clients.default.username}
  password: ${app.amqp.clients.default.password}
  virtual-host: ${app.amqp.clients.default.vhost}
  ssl.enabled: ${app.amqp.ssl.enabled:false}
  ssl.algorithm: ${app.amqp.ssl.algorithm:TLSv1.2}
  ssl.key-store: ${app.amqp.ssl.key-store:}
  ssl.key-store-password: ${app.amqp.ssl.key-store-password:}
  ssl.trust-store: ${app.amqp.ssl.trust-store:}
  ssl.trust-store-password: ${app.amqp.ssl.trust-store-password:}
